// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UpdatedToDo.Entities;

namespace UpdatedToDo.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20180117161316_useradded")]
    partial class useradded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UpdatedToDo.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("isDone");

                    b.Property<bool>("isUrgent");

                    b.Property<int?>("personId");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.HasIndex("personId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("UpdatedToDo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UpdatedToDo.Models.ToDo", b =>
                {
                    b.HasOne("UpdatedToDo.Models.User", "person")
                        .WithMany("ToDoList")
                        .HasForeignKey("personId");
                });
#pragma warning restore 612, 618
        }
    }
}
